version: '3.8'

services:
  # Neo4j图数据库服务
  neo4j:
    image: neo4j:5.12
    container_name: agno_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    restart: unless-stopped
    networks:
      - agno_network

  # vLLM服务 - Qwen2.5-7B模型
  vllm:
    image: vllm/vllm-openai:latest
    container_name: agno_vllm
    ports:
      - "8000:8000"
    volumes:
      - vllm_models:/root/.cache/huggingface
    environment:
      - MODEL_NAME=Qwen/Qwen2.5-7B-Instruct
      - PORT=8000
      - TENSOR_PARALLEL_SIZE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - agno_network

  # Milvus向量数据库
  milvus:
    image: milvusdb/milvus:v2.3.1
    container_name: agno_milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    depends_on:
      - etcd
      - minio
    restart: unless-stopped
    networks:
      - agno_network

  # Milvus依赖 - Etcd
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: agno_etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: unless-stopped
    networks:
      - agno_network

  # Milvus依赖 - MinIO
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: agno_minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data
    restart: unless-stopped
    networks:
      - agno_network

  # Agno应用服务
  agno:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agno_app
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - LLM_ENDPOINT=http://vllm:8000/v1
      - LLM_MODEL=Qwen/Qwen2.5-7B-Instruct
      - VECTOR_DB_HOST=milvus
      - VECTOR_DB_PORT=19530
      - LOG_LEVEL=INFO
    depends_on:
      - neo4j
      - vllm
      - milvus
    restart: unless-stopped
    networks:
      - agno_network

networks:
  agno_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  vllm_models:
  milvus_data:
  etcd_data:
  minio_data: 